[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-urr"
dynamic = ["version"]
description = "URL resolver utilities for Django"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Valohai", email = "info@valohai.com" },
]
maintainers = [
    { name = "Aarni Koskela", email = "akx@iki.fi" },
]
dependencies = [
    "Django>=2.0",
]

[dependency-groups]
dev = [
    "pytest-cov>=7.0.0",
    "pytest-django>=4.12.0",
    "pytest>=8.0",
]

[project.urls]
Homepage = "https://github.com/valohai/django-urr"

[tool.hatch.version]
path = "django_urr/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/django_urr",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "urrtests.settings"
norecursedirs = [".git", ".tox"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "COM",
    "I",
    "PGH",
    "UP",
]
