name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Test:
    name: Test with ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - py: "3.7"
            os: ubuntu-20.04
          - py: "3.10"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          cache: pip
      - run: python -m pip install tox tox-gh
      - run: tox
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install build && python -m build
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl
